[database]
db_node ansible_host=3.232.56.73 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[webserver]
web_node ansible_host=184.193.34.220 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa